### ISSUE TITLE
Getting 422 Http error while running github actions

### ISSUE THREAD

**Issue by adarshjayan7574** [theboi/github-update-readme#4]
**Issue description**

While running the below-mentioned github actions I am getting 422 error, do I have to enable any other options on github? 

**Observation**: Looks like"page=4" in URL parameter is causing the error

**Actions yml**

> name: CI
> on:
>   push:
>     branches:
>       - master
>   pull_request:
>     branches:
>       - master
> jobs:
>   update_readme:
>     runs-on: ubuntu-latest
>     steps:
>     - name: Update GitHub Profile README
>       uses: theboi/github-update-readme@master
>       env:
>         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>       with:
>         header: "Hey, I'm Ryan! 👋"

**Github action error**

> Run theboi/github-update-readme@master
> Failed:  RequestError [HttpError]: In order to keep the API fast for everyone, pagination is limited for this resource. Check the rel=last link relation in the Link response header to see how far back you can traverse.
>     at /home/runner/work/_actions/theboi/github-update-readme/master/node_modules/@octokit/request/dist-node/index.js:66:23
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async /home/runner/work/_actions/theboi/github-update-readme/master/index.js:26:27 {
>   name: 'HttpError',
>   status: 422,
>   headers: {
>     'access-control-allow-origin': '*',
>     'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
>     connection: 'close',
>     'content-length': '258',
>     'content-security-policy': "default-src 'none'",
>     'content-type': 'application/json; charset=utf-8',
>     date: 'Fri, 02 Oct 2020 16:28:23 GMT',
>     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
>     server: 'GitHub.com',
>     status: '422 Unprocessable Entity',
>     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
>     vary: 'Accept-Encoding, Accept, X-Requested-With',
>     'x-content-type-options': 'nosniff',
>     'x-frame-options': 'deny',
>     'x-github-media-type': 'github.v3; format=json',
>     'x-github-request-id': '0406:2EDE:3AD797:914B9C:5F775527',
>     'x-poll-interval': '60',
>     'x-ratelimit-limit': '1000',
>     'x-ratelimit-remaining': '988',
>     'x-ratelimit-reset': '1601658239',
>     'x-ratelimit-used': '12',
>     'x-xss-protection': '1; mode=block'
>   },
>   request: {
>     method: 'GET',
>     url: 'https://api.github.com/users/project-name/events?per_page=100&page=4',
>     headers: {
>       accept: 'application/vnd.github.v3+json',
>       'user-agent': 'octokit-core.js/3.1.1 Node.js/12.13.1 (linux; x64)',
>       authorization: 'token [REDACTED]'
>     },
>     request: { hook: [Function: bound bound register] }
>   },
>   documentation_url: 'https://docs.github.com/v3/#pagination'
> }
> Failed:  TypeError: Cannot read property 'data' of undefined
>     at /home/runner/work/_actions/theboi/github-update-readme/master/index.js:32:39
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> Error: Failed: 
> Error: Failed:

**Comment by theboi** [comment]
Hi there, from reading the error message I'm speculating that the Action is trying to get page 4 (100 records each) of your activity because you don't have that many repositories (by default it looks for 6 repos). I did not take this into consideration while making it oops and did not know this api limits to 300 records only. The issue should have been fixed already. 

Thanks for reporting this issue, helps a lot!
